### ISSUE TITLE
Versioning of the application

### ISSUE THREAD

**Issue by cbairy** [asticode/astilectron#12] opened 2018-11-01 09:13 UTC
Hi asticode,
I am trying to use astilectron and build an electron application. How to set the version of the application? How to make sure this version is available in windows.syso created in the application folder. Also, is there any way we can do auto-update of the application in Windows and Mac?

**Comment by asticode** [comment] 2018-11-02 09:58
@cbairy right now there's no way to set the version of the application. Why do you need it? (I've never needed it, I need to understand the use case)

As for the auto-update functionality, right now there's nothing too, but an [issue](https://github.com/asticode/go-astilectron-bootstrap/issues/1) has already been created.

**Comment by cbairy** [comment] 2018-11-02 11:42
Thanks @asticode 
Why do you need it? (I've never needed it, I need to understand the use case)
Say that I want to distribute the application created using go-astilectron. Then, I have a patch and a new feature change. I need to distribute the next version. So, this version data has to be available in menu -> about. So, I had this doubt.

**Comment by asticode** [comment] 2018-11-15 09:01
Is this related in any way to [this issue](https://github.com/asticode/go-astilectron-bootstrap/issues/1) ?

**Comment by asticode** [comment] 2018-12-19 15:11
Closing this issue as this is a duplicate of https://github.com/asticode/go-astilectron-bootstrap/issues/1

**Closed as completed by asticode** 2018-12-19 15:11 UTC
Labels: question
